# Generated by Django 5.0.6 on 2025-04-11 09:30

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=17, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='student_profile/')),
            ],
            options={
                'verbose_name': 'Administrator',
                'verbose_name_plural': 'Administrators',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AlumniRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('passout_year', models.IntegerField()),
                ('linkedin_id', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='alumni_profile/')),
            ],
            options={
                'verbose_name': 'Alumni Registration',
                'verbose_name_plural': 'Alumni Registrations',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField(blank=True, null=True)),
                ('size', models.CharField(max_length=50)),
                ('social_media_links', models.URLField(blank=True)),
                ('benefits_perks', models.TextField(blank=True)),
                ('mail_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=17, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tenth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('backlog', models.IntegerField(blank=True, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('tenth_marksheet', models.ImageField(blank=True, null=True, upload_to='student_marksheets/')),
                ('twelfth_marksheet', models.ImageField(blank=True, null=True, upload_to='student_marksheets/')),
                ('college_profile_print', models.ImageField(blank=True, null=True, upload_to='student_marksheets/')),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
                ('no_of_companies_left', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_pic', models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='student_profile/')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('interview_date', models.CharField(choices=[('25th April, 2024', '25th April, 2024'), ('24th April, 2024', '24th April, 2024')], default='25th April, 2024', max_length=100)),
                ('deadline', models.DateField()),
                ('interview_mode', models.CharField(blank=True, max_length=100)),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgpa_criteria', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('is_backlog_allowed', models.BooleanField(default=True)),
                ('no_of_openings', models.IntegerField()),
                ('job_type', models.CharField(max_length=30)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('location_flexibility', models.CharField(blank=True, max_length=100)),
                ('training_period', models.CharField(blank=True, max_length=100)),
                ('bond_timing', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='accounts.company')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='accounts.job')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
