# Generated by Django 5.0.6 on 2025-04-07 08:11

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=12)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=17, null=True)),
                ('course', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.CharField(blank=True, max_length=15, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tenth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('backlog', models.IntegerField(blank=True, default=0, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('tenth_marksheet', models.ImageField(blank=True, null=True, upload_to='student_marksheets/')),
                ('twelfth_marksheet', models.ImageField(blank=True, null=True, upload_to='student_marksheets/')),
                ('college_profile_print', models.ImageField(blank=True, null=True, upload_to='student_marksheets/')),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
                ('no_of_companies_left', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)])),
                ('profile_pic', models.ImageField(blank=True, default='/student_profile/default.jpg', null=True, upload_to='student_profile/')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
