# Generated by Django 4.2.7 on 2024-04-05 06:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('size', models.CharField(max_length=50)),
                ('social_media_links', models.URLField(blank=True)),
                ('benefits_perks', models.TextField(blank=True)),
                ('mail_id', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=10)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Prefer not to say', 'Prefer not to say')], max_length=17, null=True)),
                ('year', models.CharField(blank=True, choices=[('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth')], max_length=6, null=True)),
                ('cgpa', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('tenth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('resume', models.FileField(blank=True, null=True, upload_to='student_resumes/')),
                ('linkedin_id', models.URLField(blank=True, null=True)),
                ('github_id', models.URLField(blank=True, null=True)),
                ('profile_pic', models.ImageField(blank=True, default='/student_profile/default.gif', null=True, upload_to='student_profile/')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('interview_date', models.DateField()),
                ('deadline', models.DateField()),
                ('tenth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('twelfth_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cgpa_criteria', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('no_of_openings', models.IntegerField()),
                ('job_type', models.CharField(choices=[('full-time', 'Full Time'), ('part-time', 'Part Time'), ('internship', 'Internship'), ('contract', 'Contract')], max_length=20)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('location_flexibility', models.CharField(blank=True, max_length=100)),
                ('training_period', models.CharField(blank=True, max_length=100)),
                ('bond_timing', models.CharField(blank=True, max_length=100)),
                ('role', models.CharField(choices=[('SDE-1', 'SDE-1'), ('Full Stack', 'Full Stack Developer'), ('App Dev', 'App Developer'), ('ML Dev', 'Machine Learning Developer')], max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company')),
            ],
        ),
    ]
