# Generated by Django 4.2.19 on 2025-04-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instagram_id',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='twitter_id',
            field=models.URLField(blank=True, null=True),
        ),
    ]
