# Generated by Django 4.2.19 on 2025-04-13 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_student_instagram_id_student_twitter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(default='/student_profile/default.jpg', upload_to='student_profile/'),
        ),
    ]
