# Generated by Django 5.0.6 on 2025-04-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_administrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='backlog',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
