# Generated by Django 4.2.19 on 2025-04-13 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='administrator',
            name='profile_pic',
            field=models.ImageField(default='/student_profile/default.jpg', upload_to='student_profile/'),
        ),
    ]
