# Generated by Django 4.2.7 on 2024-04-08 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_student_profile_pic_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='slug',
            field=models.SlugField(default='', max_length=100, unique=True),
        ),
    ]
