# Generated by Django 4.2.19 on 2025-04-13 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_administrator_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_of_companies_left',
            field=models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
