# Generated by Django 4.2.19 on 2025-04-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_student_no_of_companies_left'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='alumni_status',
            field=models.CharField(choices=[('Current Student', 'Current Student'), ('Alumni', 'Alumni')], default='Current Student', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='passout_year',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
