# Generated by Django 4.2.7 on 2024-04-09 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interview_date',
            field=models.DateTimeField(),
        ),
    ]
