# Generated by Django 4.2.7 on 2024-04-10 04:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_job_interview_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='no_of_companies_left',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(2), django.core.validators.MinValueValidator(0)]),
        ),
    ]
