# Generated by Django 4.2.19 on 2025-04-13 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_add_student_alumni_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='college_profile_print',
            field=models.FileField(blank=True, null=True, upload_to='student_marksheets/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='tenth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='student_marksheets/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='twelfth_marksheet',
            field=models.FileField(blank=True, null=True, upload_to='student_marksheets/'),
        ),
    ]
