# Generated by Django 4.2.19 on 2025-04-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_student_college_profile_print_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university_roll_no',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='interview_date',
            field=models.CharField(choices=[('17th April, 2025', '17th April, 2025'), ('18th April, 2025', '18th April, 2025'), ('19th April, 2025', '19th April, 2025')], default='17th April, 2025', max_length=100),
        ),
    ]
