# Generated by Django 4.2.7 on 2025-04-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_volunteer_remove_student_university_roll_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(blank=True, help_text='Comma-separated list of courses', max_length=500, null=True),
        ),
    ]
