# Generated by Django 4.2.7 on 2024-04-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_job_job_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cgpa_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='student_marksheets/'),
        ),
        migrations.AddField(
            model_name='student',
            name='tenth_marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='student_marksheets/'),
        ),
        migrations.AddField(
            model_name='student',
            name='twelfth_marksheet',
            field=models.ImageField(blank=True, null=True, upload_to='student_marksheets/'),
        ),
    ]
