# Generated by Django 4.2.7 on 2025-04-16 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_savedfilter'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='bypass_eligibility',
            field=models.BooleanField(default=False, help_text='If enabled, bypasses all eligibility restrictions like CGPA, 10th, 12th marks'),
        ),
        migrations.DeleteModel(
            name='SavedFilter',
        ),
    ]
