# Generated by Django 4.2.7 on 2024-04-13 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_student_cgpa_screenshot_student_tenth_marksheet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='cgpa_screenshot',
            new_name='college_profile_print',
        ),
    ]
