# Generated by Django 4.2.7 on 2025-04-17 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_student_bypass_eligibility_delete_savedfilter'),
    ]

    operations = [
    ]
