# Generated by Django 4.2.7 on 2025-04-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_add_bypass_eligibility'),
    ]

    operations = [
    ]
