# Generated by Django 4.2.7 on 2024-04-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_company_mail_id_alter_company_website_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlumniRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=12)),
                ('company', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('passout_year', models.IntegerField()),
                ('linkedin_id', models.URLField(blank=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='alumni_profile/')),
            ],
            options={
                'verbose_name': 'Alumni Registration',
                'verbose_name_plural': 'Alumni Registrations',
            },
        ),
    ]
