# Generated by Django 4.2.7 on 2025-04-17 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_add_bypass_eligibility_column_if_missing'),
    ]

    operations = [
    ]
