# Generated by Django 4.2.7 on 2024-04-18 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alumniregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='backlog',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='interview_mode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
