# Generated by Django 4.2.7 on 2024-04-18 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_job_backlog_job_interview_mode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='backlog',
        ),
        migrations.AddField(
            model_name='student',
            name='backlog',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
