# Generated by Django 4.2.7 on 2024-04-18 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_remove_job_backlog_student_backlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_backlog_allowed',
            field=models.BooleanField(default=True),
        ),
    ]
