# Generated by Django 4.2.7 on 2024-04-19 07:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_job_is_backlog_allowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interview_date',
            field=models.CharField(blank=True, choices=[('24th April, 2024', '24th April, 2024'), ('25th April, 2024', '25th April, 2024')], default='25th April, 2024', max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='no_of_companies_left',
            field=models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
