# Generated by Django 4.2.7 on 2024-04-19 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_job_interview_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='interview_date',
            field=models.CharField(choices=[('24th April, 2024', '24th April, 2024'), ('25th April, 2024', '25th April, 2024')], default='25th April, 2024', max_length=100),
        ),
    ]
