# Generated by Django 4.2.19 on 2025-04-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_carousel',
            name='day',
            field=models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3')], default=1),
        ),
    ]
